services:
  m3u8-downloader:
    container_name: Mt
    image: okhao/mt:latest
    ports:
      - "9151:8080"
    volumes:
      - /root/docker/video:/downloads
      - ./data:/app/data
    restart: unless-stopped
